/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        display: ['Playfair Display', 'serif'],
        body: ['DM Sans', 'sans-serif'],
      },
      colors: {
        cream: '#FAF7F0',
        'cream-dark': '#F2EDE2',
        olive: '#6B7C5E',
        'olive-light': '#8A9B7D',
        'olive-dark': '#4A5840',
        rosso: '#C0392B',
        'rosso-light': '#E8A09A',
        'rosso-pale': '#F9EDED',
        terracotta: '#C07A5B',
        'terracotta-light': '#E8C4B0',
        gold: '#B8860B',
        'gold-light': '#D4A017',
        'text-dark': '#2C1810',
        'text-medium': '#5A4A42',
        'text-light': '#9A8A82',
        // Legacy
        'bg-primary': '#FAF7F0',
        'bg-secondary': '#F2EDE2',
        'bg-tertiary': '#EAE4D8',
        'text-primary': '#2C1810',
        'text-muted': '#9A8A82',
        'gold-dark': '#8B6B00',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        '2xl': '20px',
        '3xl': '28px',
        'full': '100px',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'fade-up': { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-up': 'fade-up 0.6s ease forwards',
        'fade-in': 'fade-in 0.4s ease forwards',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    'bg-olive', 'text-olive', 'border-olive',
    'bg-rosso', 'text-rosso',
    'bg-terracotta', 'text-terracotta',
    'bg-cream', 'bg-cream-dark',
    'text-dark', 'text-medium',
  ],
}